package com.example.server.enums;

public enum ProjectAuthority {
    CREATE_ORGANIZATION,
    CREATE_TEAM,
    CREATE_PROJECT,
    CREATE_TASKS,
    VIEW_PROJECT,
    VIEW_TEAM,
    DELETE_TEAM,
    DELETE_TIMELOG,
    VIEW_TASKS,
    EDIT_PROJECT,
    DELETE_PROJECT,
    ASSIGN_TASKS,
    EDIT_TASKS,
    DELETE_TASKS,
    VIEW_REPORTS,
    EDIT_REPORTS,
    ACCEPT_MEMBERS


}
